.TH "phenogene/ Directory Reference" 3 "Sun Jun 23 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFileManager\&.h\fP"
.br
.ti -1c
.RI "file \fBFM\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFM_getters\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFM_setters\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGeneral_Notation\&.h\fP"
.br
.ti -1c
.RI "file \fBGUI\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGUI\&.h\fP"
.br
.ti -1c
.RI "file \fBGUI_constructor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGUI_startButton\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNeuralNetwork\&.h\fP"
.br
.ti -1c
.RI "file \fBNN\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNN_constructor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNN_getters\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNN_setters\&.cpp\fP"
.br
.in -1c
