File_Manager
NAME
File_Manager -
SYNOPSIS
#include <FileManager.h>
Public Member Functions
File_Manager ()
void set_input_file (string)
Set input file path to string s.
void set_expected_out_file (string)
Set expected output file path to string s.
void set_output_file (string)
Set calculated output file path to string s.
void set_weights_file (string)
Set weights file path to string s.
void set_rank_output_strings (int, string)
Set string with index i to s.
string get_read_ex_output_string ()
Get string expected output content.
string get_input_population_string ()
Get string input content.
string get_output_population_string ()
Get string output content.
string get_rank_output_strings (int)
Get string represenation for given ID.
void do_function (int)
Call rotine specified by parameter mode.
void fill_rank_output ()
Interface to fill the output/decimal association
 associates each output node with a string. "
Public Attributes
Neural_Network n
Private Member Functions
void read_input (string)
Opens file filePath and reads its content.
void read_expected_output (string)
Read expected output
 Opens file filePath and reads its content. "
void read_weights (string)
Read weights for hidden and output layer.
 Opens file filePath and reads its content. "
void write_output (string)
Write output
 Opens file filePath and write to it. "
void write_weights (string)
Write weights
 Opens file filePath and write to it. "
string convertInt (int)
Converts integer number to string.
Private Attributes
ofstream write
ifstream read
string read_ex_output_string
string input_population_string
string output_population_string
string input_file
string expected_out_file
string output_file
string weights_file
string rank_output_strings [output_l]
int ids [max_dataset_size]
Detailed Description
Definition at line 7 of file FileManager.h.
Constructor & Destructor Documentation
File_Manager::File_Manager ()
Definition at line 3 of file FM.cpp.
Member Function Documentation
string File_Manager::convertInt (intnumber) [private]
Converts integer number to string. Parameters:
[number] Integer to be converted.
Returns:
Number in string format.
Definition at line 212 of file FM.cpp.
void File_Manager::do_function (intmode)
Call rotine specified by parameter mode. Parameters:
[mode] mode = 1: read from input file
 mode = 2: write to output file
 mode = 3: read from weights file
 mode = 4: write to weights file
Definition at line 15 of file FM.cpp.
References expected_out_file, input_file, output_file, read_expected_output(), read_input(), read_weights(), weights_file, write_output(), and write_weights().
void File_Manager::fill_rank_output ()
Interface to fill the output/decimal association
 associates each output node with a string. Postcondition:
Output_rank is filled.
Rank_output is filled.
Definition at line 234 of file FM.cpp.
References fori, n, Neural_Network::output_len, Neural_Network::output_rank, Neural_Network::rank_output, and rank_output_strings.
string File_Manager::get_input_population_string ()
Get string input content.
Definition at line 13 of file FM_getters.cpp.
References input_population_string.
string File_Manager::get_output_population_string ()
Get string output content.
Definition at line 20 of file FM_getters.cpp.
References output_population_string.
string File_Manager::get_rank_output_strings (inti)
Get string represenation for given ID.
Definition at line 27 of file FM_getters.cpp.
References rank_output_strings.
string File_Manager::get_read_ex_output_string ()
Get string expected output content.
Definition at line 6 of file FM_getters.cpp.
References read_ex_output_string.
void File_Manager::read_expected_output (stringfilePath) [private]
Read expected output
 Opens file filePath and reads its content. Parameters:
[filePath] File path to be read.
Precondition:
File specified by filePath is in the correct format.
Postcondition:
Expected output dataset is filled.
Definition at line 101 of file FM.cpp.
References Neural_Network::dataset_size, Neural_Network::expected_o, fori, forj, max_dataset_size, n, Neural_Network::output_dataset, Neural_Network::output_len, Neural_Network::output_rank, read, and read_ex_output_string.
void File_Manager::read_input (stringfilePath) [private]
Opens file filePath and reads its content. *Read input
Parameters:
[filePath] File path to be read.
Precondition:
File specified by filePath is in the correct format.
Postcondition:
Input dataset is filled.
Definition at line 46 of file FM.cpp.
References convertInt(), Neural_Network::dataset_size, fori, fork, ids, Neural_Network::input, Neural_Network::input_dataset, Neural_Network::input_len, input_population_string, Neural_Network::input_rank, max_dataset_size, n, and read.
void File_Manager::read_weights (stringfilePath) [private]
Read weights for hidden and output layer.
 Opens file filePath and reads its content. Parameters:
[filePath] File path to be read.
Precondition:
File specified by filePath is in the correct format.
Postcondition:
Weights datasets are filled.
Definition at line 173 of file FM.cpp.
References fori, forj, Neural_Network::hidden_len, Neural_Network::input_len, n, Neural_Network::output_len, read, Neural_Network::Wh, and Neural_Network::Wo.
void File_Manager::set_expected_out_file (strings)
Set expected output file path to string s. Parameters:
[string s] expected output file path
Definition at line 16 of file FM_setters.cpp.
References expected_out_file.
void File_Manager::set_input_file (strings)
Set input file path to string s. Parameters:
[string s] input file path
Definition at line 7 of file FM_setters.cpp.
References input_file.
void File_Manager::set_output_file (strings)
Set calculated output file path to string s. Parameters:
[string s] output file path
Definition at line 25 of file FM_setters.cpp.
References output_file.
void File_Manager::set_rank_output_strings (inti, strings)
Set string with index i to s. Parameters:
[int i] Index i of rank_output_strings
[string s] Output keyword
Definition at line 45 of file FM_setters.cpp.
References rank_output_strings.
void File_Manager::set_weights_file (strings)
Set weights file path to string s. Parameters:
[string s] weights file path
Definition at line 34 of file FM_setters.cpp.
References weights_file.
void File_Manager::write_output (stringfilePath) [private]
Write output
 Opens file filePath and write to it. Parameters:
[filePath] File path to be wrote.
Precondition:
Directory specified by filePath is accessible.
Postcondition:
Output file to be found in the specified directory.
Definition at line 136 of file FM.cpp.
References convertInt(), Neural_Network::dataset_size, fori, forj, ids, n, Neural_Network::output_dataset, Neural_Network::output_len, output_population_string, Neural_Network::rank_output, and write.
void File_Manager::write_weights (stringfilePath) [private]
Write weights
 Opens file filePath and write to it. Parameters:
[filePath] File path to be wrote.
Precondition:
Directory specified by filePath is accessible.
Postcondition:
Weights file to be found in the specified directory.
Definition at line 194 of file FM.cpp.
References fori, forj, Neural_Network::hidden_len, Neural_Network::input_len, n, Neural_Network::output_len, Neural_Network::Wh, Neural_Network::Wo, and write.
Member Data Documentation
string File_Manager::expected_out_file [private]
Definition at line 38 of file FileManager.h.
int File_Manager::ids[max_dataset_size] [private]
Definition at line 42 of file FileManager.h.
string File_Manager::input_file [private]
Definition at line 37 of file FileManager.h.
string File_Manager::input_population_string [private]
Definition at line 35 of file FileManager.h.
Neural_Network File_Manager::n
Definition at line 12 of file FileManager.h.
string File_Manager::output_file [private]
Definition at line 39 of file FileManager.h.
string File_Manager::output_population_string [private]
Definition at line 36 of file FileManager.h.
string File_Manager::rank_output_strings[output_l] [private]
Definition at line 41 of file FileManager.h.
ifstream File_Manager::read [private]
Definition at line 33 of file FileManager.h.
string File_Manager::read_ex_output_string [private]
Definition at line 34 of file FileManager.h.
string File_Manager::weights_file [private]
Definition at line 40 of file FileManager.h.
ofstream File_Manager::write [private]
Definition at line 32 of file FileManager.h.
Author
Generated automatically by Doxygen from the source code.