.TH "phenogene/General_Notation.h" 3 "Fri Jun 21 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/General_Notation.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <map>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBfori\fP(a, b)   for (int i = (a); i < (b); i++)"
.br
.ti -1c
.RI "#define \fBforj\fP(a, b)   for (int j = (a); j < (b); j++)"
.br
.ti -1c
.RI "#define \fBfork\fP(a, b)   for (int k = (a); k < (b); k++)"
.br
.ti -1c
.RI "#define \fBmax_dataset_size\fP   10000"
.br
.ti -1c
.RI "#define \fBinput_l\fP   100"
.br
.ti -1c
.RI "#define \fBoutput_l\fP   100"
.br
.ti -1c
.RI "#define \fBhidden_l\fP   100"
.br
.ti -1c
.RI "#define \fBhidden_layer\fP   0"
.br
.ti -1c
.RI "#define \fBoutput_layer\fP   1"
.br
.ti -1c
.RI "#define \fBsegmoidal\fP   1"
.br
.ti -1c
.RI "#define \fBmax_iterations\fP   10000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define fori(a, b)   for (int i = (a); i < (b); i++)"

.PP
Definition at line 17 of file General_Notation\&.h\&.
.SS "#define forj(a, b)   for (int j = (a); j < (b); j++)"

.PP
Definition at line 18 of file General_Notation\&.h\&.
.SS "#define fork(a, b)   for (int k = (a); k < (b); k++)"

.PP
Definition at line 19 of file General_Notation\&.h\&.
.SS "#define hidden_l   100"

.PP
Definition at line 23 of file General_Notation\&.h\&.
.SS "#define hidden_layer   0"

.PP
Definition at line 24 of file General_Notation\&.h\&.
.SS "#define input_l   100"

.PP
Definition at line 21 of file General_Notation\&.h\&.
.SS "#define max_dataset_size   10000"

.PP
Definition at line 20 of file General_Notation\&.h\&.
.SS "#define max_iterations   10000"

.PP
Definition at line 27 of file General_Notation\&.h\&.
.SS "#define output_l   100"

.PP
Definition at line 22 of file General_Notation\&.h\&.
.SS "#define output_layer   1"

.PP
Definition at line 25 of file General_Notation\&.h\&.
.SS "#define segmoidal   1"

.PP
Definition at line 26 of file General_Notation\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
