.TH "GUI" 3 "Sat Jun 22 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GUI\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGUI\fP (QWidget *parent=0)"
.br
.RI "\fI\fBGUI\fP class constructor\&. \fP"
.ti -1c
.RI "\fB~GUI\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBon_quitButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_clicked\fP ()"
.br
.RI "\fICalled when start button is pushed\&.
.br
 Determines weather to train/test/analyze, according to the opened tab\&. \fP"
.ti -1c
.RI "void \fBon_pushButton_3_clicked\fP ()"
.br
.RI "\fIBrowses Expected Output File
.br
 Allows the user to select a file\&. \fP"
.ti -1c
.RI "void \fBon_pushButton_4_clicked\fP ()"
.br
.RI "\fIBrowses Input File
.br
 Allows the user to select a file\&. \fP"
.ti -1c
.RI "void \fBon_pushButton_5_clicked\fP ()"
.br
.RI "\fIBrowses Input File
.br
 Allows the user to select a file\&. \fP"
.ti -1c
.RI "void \fBon_pushButton_6_clicked\fP ()"
.br
.RI "\fIBrowses Weights File
.br
 Allows the user to select a file\&. \fP"
.ti -1c
.RI "void \fBon_lineEdit_editingFinished\fP ()"
.br
.RI "\fISet gene number, aka, input nodes number\&. \fP"
.ti -1c
.RI "void \fBon_lineEdit_3_editingFinished\fP ()"
.br
.RI "\fISet learning rate\&. \fP"
.ti -1c
.RI "void \fBon_lineEdit_4_editingFinished\fP ()"
.br
.RI "\fISet Acceptable Error\&. \fP"
.ti -1c
.RI "void \fBon_textEdit_4_textChanged\fP ()"
.br
.RI "\fISet output keywords\&. \fP"
.ti -1c
.RI "void \fBon_lineEdit_5_editingFinished\fP ()"
.br
.RI "\fISet hidden nodes numbers\&. \fP"
.ti -1c
.RI "void \fBon_lineEdit_7_editingFinished\fP ()"
.br
.RI "\fISet momentum\&. \fP"
.ti -1c
.RI "void \fBon_lineEdit_10_editingFinished\fP ()"
.br
.RI "\fISet maximum iterations number\&. \fP"
.ti -1c
.RI "void \fBon_tabWidget_currentChanged\fP (int index)"
.br
.RI "\fIChange the view when a user changes tab\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "QString \fBvalid_input\fP ()"
.br
.RI "\fICheck that all input needed is filled\&. \fP"
.ti -1c
.RI "void \fBfill_rank\fP ()"
.br
.RI "\fICalled once before a train/test is performed\&. \fP"
.ti -1c
.RI "void \fBperform_train\fP ()"
.br
.RI "\fICalls file manager rotines to train:
.br
\&. \fP"
.ti -1c
.RI "void \fBperform_test\fP ()"
.br
.ti -1c
.RI "void \fBset_validators\fP ()"
.br
.RI "\fISet validators for user input\&. \fP"
.ti -1c
.RI "void \fBset_styleSheet\fP ()"
.br
.RI "\fISet style sheet configuration: Set color grey for some labels\&. \fP"
.ti -1c
.RI "void \fBdisplay_error\fP (QString)"
.br
.RI "\fIDisplays the error message contained in string er\&. \fP"
.ti -1c
.RI "void \fBprepare_report\fP ()"
.br
.RI "\fIPrepare analysis report\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString \fBfilePath\fP"
.br
.ti -1c
.RI "QFileDialog \fBfileDialog\fP"
.br
.ti -1c
.RI "QByteArray \fBstate\fP"
.br
.ti -1c
.RI "Ui::GUI * \fBui\fP"
.br
.ti -1c
.RI "\fBFile_Manager\fP \fBfm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file GUI\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GUI::GUI (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBGUI\fP class constructor\&. 
.PP
Definition at line 8 of file GUI_constructor\&.cpp\&.
.PP
References set_styleSheet(), and set_validators()\&.
.SS "GUI::~GUI ()"

.PP
Definition at line 54 of file GUI_constructor\&.cpp\&.
.PP
References ui\&.
.SH "Member Function Documentation"
.PP 
.SS "void GUI::display_error (QStringer)\fC [private]\fP"

.PP
Displays the error message contained in string er\&. \fBParameters:\fP
.RS 4
\fI[Qstring\fP er] Error message to be displayed\&. 
.RE
.PP

.PP
Definition at line 131 of file GUI_startButton\&.cpp\&.
.SS "void GUI::fill_rank ()\fC [private]\fP"

.PP
Called once before a train/test is performed\&. \fBPostcondition:\fP
.RS 4
Rank-Output Strings are filled\&. 
.RE
.PP

.PP
Definition at line 116 of file GUI_startButton\&.cpp\&.
.PP
References fm, File_Manager::set_rank_output_strings(), and ui\&.
.SS "void GUI::on_lineEdit_10_editingFinished ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set maximum iterations number\&. On Analysis Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid double number\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Maximum iterations number is changed\&. 
.RE
.PP

.PP
Definition at line 180 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_max_it(), and ui\&.
.SS "void GUI::on_lineEdit_3_editingFinished ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set learning rate\&. On Train Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid double number\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Learning rate is set\&. 
.RE
.PP

.PP
Definition at line 61 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_learning_rate(), and ui\&.
.SS "void GUI::on_lineEdit_4_editingFinished ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set Acceptable Error\&. On Train Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid double number\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Minimum error is set\&. 
.RE
.PP

.PP
Definition at line 73 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_minimum_error(), and ui\&.
.SS "void GUI::on_lineEdit_5_editingFinished ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set hidden nodes numbers\&. On Analysis Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid integer number\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Hidden nodes is changed\&. 
.RE
.PP

.PP
Definition at line 158 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_hidden_len(), and ui\&.
.SS "void GUI::on_lineEdit_7_editingFinished ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set momentum\&. On Analysis Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid double number\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Momentum is changed\&. 
.RE
.PP

.PP
Definition at line 169 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_momentum(), and ui\&.
.SS "void GUI::on_lineEdit_editingFinished ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set gene number, aka, input nodes number\&. On Train Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid integer number\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Input nodes number is set\&. 
.RE
.PP

.PP
Definition at line 48 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_input_len(), and ui\&.
.SS "void GUI::on_pushButton_3_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Browses Expected Output File
.br
 Allows the user to select a file\&. On Train Tab 
.PP
\fBPrecondition:\fP
.RS 4
Expected-Output browse button is clicked\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
File path to expected output file is set\&. 
.RE
.PP

.PP
Definition at line 33 of file GUI\&.cpp\&.
.PP
References fileDialog, filePath, fm, File_Manager::set_expected_out_file(), and ui\&.
.SS "void GUI::on_pushButton_4_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Browses Input File
.br
 Allows the user to select a file\&. On Predict Tab 
.PP
\fBPrecondition:\fP
.RS 4
Input browse button is clicked\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
File path to input file is set\&. 
.RE
.PP

.PP
Definition at line 109 of file GUI\&.cpp\&.
.PP
References fileDialog, filePath, fm, File_Manager::set_input_file(), File_Manager::set_output_file(), and ui\&.
.SS "void GUI::on_pushButton_5_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Browses Input File
.br
 Allows the user to select a file\&. On Train Tab 
.PP
\fBPrecondition:\fP
.RS 4
Input browse button is clicked\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
File path to input file is set\&. 
.RE
.PP

.PP
Definition at line 12 of file GUI\&.cpp\&.
.PP
References fileDialog, filePath, fm, File_Manager::set_input_file(), File_Manager::set_output_file(), File_Manager::set_weights_file(), and ui\&.
.SS "void GUI::on_pushButton_6_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Browses Weights File
.br
 Allows the user to select a file\&. On Predict Tab 
.PP
\fBPrecondition:\fP
.RS 4
Weights change button is clicked\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
File path to weights file is set\&. 
.RE
.PP

.PP
Definition at line 126 of file GUI\&.cpp\&.
.PP
References fileDialog, filePath, fm, File_Manager::set_weights_file(), and ui\&.
.SS "void GUI::on_pushButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Called when start button is pushed\&.
.br
 Determines weather to train/test/analyze, according to the opened tab\&. 
.PP
Definition at line 9 of file GUI_startButton\&.cpp\&.
.PP
References display_error(), File_Manager::fill_rank_output(), fm, perform_test(), perform_train(), prepare_report(), ui, and valid_input()\&.
.SS "void GUI::on_quitButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 186 of file GUI\&.cpp\&.
.SS "void GUI::on_tabWidget_currentChanged (intindex)\fC [private]\fP, \fC [slot]\fP"

.PP
Change the view when a user changes tab\&. On Analysis Tab 
.PP
Definition at line 138 of file GUI\&.cpp\&.
.PP
References ui\&.
.SS "void GUI::on_textEdit_4_textChanged ()\fC [private]\fP, \fC [slot]\fP"

.PP
Set output keywords\&. On Train Tab 
.PP
\fBPrecondition:\fP
.RS 4
Entered is a valid strings\&. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
Output nodes number is set\&. 
.RE
.PP

.PP
Definition at line 86 of file GUI\&.cpp\&.
.PP
References fm, File_Manager::n, Neural_Network::set_output_len(), and ui\&.
.SS "void GUI::perform_test ()\fC [private]\fP"
\fBParameters:\fP
.RS 4
\fICalls\fP file manager rotines to test\&.
.br
.IP "1." 4
read input\&.
.br

.IP "2." 4
read weights\&.
.br

.IP "3." 4
test\&.
.br

.IP "4." 4
write output\&.
.br
 
.PP
.RE
.PP

.PP
Definition at line 60 of file GUI_startButton\&.cpp\&.
.PP
References File_Manager::do_function(), Neural_Network::do_function(), fm, File_Manager::get_input_population_string(), File_Manager::get_output_population_string(), File_Manager::n, and ui\&.
.SS "void GUI::perform_train ()\fC [private]\fP"

.PP
Calls file manager rotines to train:
.br
\&. .IP "1." 4
read input\&.
.br

.IP "2." 4
read expected output\&.
.br

.IP "3." 4
train\&.
.br

.IP "4." 4
write weights\&. 
.PP

.PP
Definition at line 35 of file GUI_startButton\&.cpp\&.
.PP
References File_Manager::do_function(), Neural_Network::do_function(), fm, File_Manager::get_input_population_string(), File_Manager::get_read_ex_output_string(), File_Manager::n, and ui\&.
.SS "void GUI::prepare_report ()\fC [private]\fP"

.PP
Prepare analysis report\&. 
.PP
Definition at line 144 of file GUI_startButton\&.cpp\&.
.PP
References fm, Neural_Network::get_hidden_len(), Neural_Network::get_input_len(), Neural_Network::get_max_it(), Neural_Network::get_momentum(), Neural_Network::get_output_len(), File_Manager::n, and ui\&.
.SS "void GUI::set_styleSheet ()\fC [private]\fP"

.PP
Set style sheet configuration: Set color grey for some labels\&. 
.PP
Definition at line 20 of file GUI_constructor\&.cpp\&.
.PP
References ui\&.
.SS "void GUI::set_validators ()\fC [private]\fP"

.PP
Set validators for user input\&. 
.PP
Definition at line 34 of file GUI_constructor\&.cpp\&.
.PP
References ui\&.
.SS "QString GUI::valid_input ()\fC [private]\fP"

.PP
Check that all input needed is filled\&. 
.PP
Definition at line 79 of file GUI_startButton\&.cpp\&.
.PP
References fill_rank(), fm, fori, Neural_Network::get_output_len(), File_Manager::get_rank_output_strings(), File_Manager::n, and ui\&.
.SH "Member Data Documentation"
.PP 
.SS "QFileDialog GUI::fileDialog\fC [private]\fP"

.PP
Definition at line 21 of file GUI\&.h\&.
.SS "QString GUI::filePath\fC [private]\fP"

.PP
Definition at line 20 of file GUI\&.h\&.
.SS "\fBFile_Manager\fP GUI::fm\fC [private]\fP"

.PP
Definition at line 48 of file GUI\&.h\&.
.SS "QByteArray GUI::state\fC [private]\fP"

.PP
Definition at line 22 of file GUI\&.h\&.
.SS "Ui::GUI* GUI::ui\fC [private]\fP"

.PP
Definition at line 46 of file GUI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
