.TH "phenogene/GUI.h" 3 "Sun Jun 23 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/GUI.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <qapplication\&.h>\fP
.br
\fC#include <qmainwindow\&.h>\fP
.br
\fC#include <qvalidator\&.h>\fP
.br
\fC#include <qlineedit\&.h>\fP
.br
\fC#include <QRegExp>\fP
.br
\fC#include <FileManager\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGUI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
