GUI
NAME
GUI -
SYNOPSIS
#include <GUI.h>
Public Member Functions
GUI (QWidget *parent=0)
GUI class constructor.
~GUI ()
Private Slots
void on_quitButton_clicked ()
void on_pushButton_clicked ()
Called when start button is pushed.
 Determines weather to train/test/analyze, according to the opened tab. "
void on_pushButton_3_clicked ()
Browses Expected Output File
 Allows the user to select a file. "
void on_pushButton_4_clicked ()
Browses Input File
 Allows the user to select a file. "
void on_pushButton_5_clicked ()
Browses Input File
 Allows the user to select a file. "
void on_pushButton_6_clicked ()
Browses Weights File
 Allows the user to select a file. "
void on_lineEdit_editingFinished ()
Set gene number, aka, input nodes number.
void on_lineEdit_3_editingFinished ()
Set learning rate.
void on_lineEdit_4_editingFinished ()
Set Acceptable Error.
void on_textEdit_4_textChanged ()
Set output keywords.
void on_lineEdit_5_editingFinished ()
Set hidden nodes numbers.
void on_lineEdit_7_editingFinished ()
Set momentum.
void on_lineEdit_10_editingFinished ()
Set maximum iterations number.
void on_tabWidget_currentChanged (int index)
Change the view when a user changes tab.
Private Member Functions
QString valid_input ()
Check that all input needed is filled.
void fill_rank ()
Called once before a train/test is performed.
void perform_train ()
Calls file manager rotines to train:
. "
void perform_test ()
void set_validators ()
Set validators for user input.
void set_styleSheet ()
Set style sheet configuration: Set color grey for some labels.
void display_error (QString)
Displays the error message contained in string er.
void prepare_report ()
Prepare analysis report.
Private Attributes
QString filePath
QFileDialog fileDialog
QByteArray state
Ui::GUI * ui
File_Manager fm
Detailed Description
Definition at line 18 of file GUI.h.
Constructor & Destructor Documentation
GUI::GUI (QWidget *parent = 0) [explicit]
GUI class constructor.
Definition at line 8 of file GUI_constructor.cpp.
References set_styleSheet(), and set_validators().
GUI::~GUI ()
Definition at line 54 of file GUI_constructor.cpp.
References ui.
Member Function Documentation
void GUI::display_error (QStringer) [private]
Displays the error message contained in string er. Parameters:
[Qstring er] Error message to be displayed.
Definition at line 131 of file GUI_startButton.cpp.
void GUI::fill_rank () [private]
Called once before a train/test is performed. Postcondition:
Rank-Output Strings are filled.
Definition at line 116 of file GUI_startButton.cpp.
References fm, File_Manager::set_rank_output_strings(), and ui.
void GUI::on_lineEdit_10_editingFinished () [private], [slot]
Set maximum iterations number. On Analysis Tab
Precondition:
Entered is a valid double number.
Postcondition:
Maximum iterations number is changed.
Definition at line 180 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_max_it(), and ui.
void GUI::on_lineEdit_3_editingFinished () [private], [slot]
Set learning rate. On Train Tab
Precondition:
Entered is a valid double number.
Postcondition:
Learning rate is set.
Definition at line 61 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_learning_rate(), and ui.
void GUI::on_lineEdit_4_editingFinished () [private], [slot]
Set Acceptable Error. On Train Tab
Precondition:
Entered is a valid double number.
Postcondition:
Minimum error is set.
Definition at line 73 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_minimum_error(), and ui.
void GUI::on_lineEdit_5_editingFinished () [private], [slot]
Set hidden nodes numbers. On Analysis Tab
Precondition:
Entered is a valid integer number.
Postcondition:
Hidden nodes is changed.
Definition at line 158 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_hidden_len(), and ui.
void GUI::on_lineEdit_7_editingFinished () [private], [slot]
Set momentum. On Analysis Tab
Precondition:
Entered is a valid double number.
Postcondition:
Momentum is changed.
Definition at line 169 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_momentum(), and ui.
void GUI::on_lineEdit_editingFinished () [private], [slot]
Set gene number, aka, input nodes number. On Train Tab
Precondition:
Entered is a valid integer number.
Postcondition:
Input nodes number is set.
Definition at line 48 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_input_len(), and ui.
void GUI::on_pushButton_3_clicked () [private], [slot]
Browses Expected Output File
 Allows the user to select a file. On Train Tab
Precondition:
Expected-Output browse button is clicked.
Postcondition:
File path to expected output file is set.
Definition at line 33 of file GUI.cpp.
References fileDialog, filePath, fm, File_Manager::set_expected_out_file(), and ui.
void GUI::on_pushButton_4_clicked () [private], [slot]
Browses Input File
 Allows the user to select a file. On Predict Tab
Precondition:
Input browse button is clicked.
Postcondition:
File path to input file is set.
Definition at line 109 of file GUI.cpp.
References fileDialog, filePath, fm, File_Manager::set_input_file(), File_Manager::set_output_file(), and ui.
void GUI::on_pushButton_5_clicked () [private], [slot]
Browses Input File
 Allows the user to select a file. On Train Tab
Precondition:
Input browse button is clicked.
Postcondition:
File path to input file is set.
Definition at line 12 of file GUI.cpp.
References fileDialog, filePath, fm, File_Manager::set_input_file(), File_Manager::set_output_file(), File_Manager::set_weights_file(), and ui.
void GUI::on_pushButton_6_clicked () [private], [slot]
Browses Weights File
 Allows the user to select a file. On Predict Tab
Precondition:
Weights change button is clicked.
Postcondition:
File path to weights file is set.
Definition at line 126 of file GUI.cpp.
References fileDialog, filePath, fm, File_Manager::set_weights_file(), and ui.
void GUI::on_pushButton_clicked () [private], [slot]
Called when start button is pushed.
 Determines weather to train/test/analyze, according to the opened tab.
Definition at line 9 of file GUI_startButton.cpp.
References display_error(), File_Manager::fill_rank_output(), fm, perform_test(), perform_train(), prepare_report(), ui, and valid_input().
void GUI::on_quitButton_clicked () [private], [slot]
Definition at line 186 of file GUI.cpp.
void GUI::on_tabWidget_currentChanged (intindex) [private], [slot]
Change the view when a user changes tab. On Analysis Tab
Definition at line 138 of file GUI.cpp.
References ui.
void GUI::on_textEdit_4_textChanged () [private], [slot]
Set output keywords. On Train Tab
Precondition:
Entered is a valid strings.
Postcondition:
Output nodes number is set.
Definition at line 86 of file GUI.cpp.
References fm, File_Manager::n, Neural_Network::set_output_len(), and ui.
void GUI::perform_test () [private]
Parameters:
Calls file manager rotines to test.
1.
read input.
2.
read weights.
3.
test.
4.
write output.
Definition at line 60 of file GUI_startButton.cpp.
References File_Manager::do_function(), Neural_Network::do_function(), fm, File_Manager::get_input_population_string(), File_Manager::get_output_population_string(), File_Manager::n, and ui.
void GUI::perform_train () [private]
Calls file manager rotines to train:
. .IP "1." 4
read input.
2.
read expected output.
3.
train.
4.
write weights.
Definition at line 35 of file GUI_startButton.cpp.
References File_Manager::do_function(), Neural_Network::do_function(), fm, File_Manager::get_input_population_string(), File_Manager::get_read_ex_output_string(), File_Manager::n, and ui.
void GUI::prepare_report () [private]
Prepare analysis report.
Definition at line 144 of file GUI_startButton.cpp.
References fm, Neural_Network::get_hidden_len(), Neural_Network::get_input_len(), Neural_Network::get_max_it(), Neural_Network::get_momentum(), Neural_Network::get_output_len(), File_Manager::n, and ui.
void GUI::set_styleSheet () [private]
Set style sheet configuration: Set color grey for some labels.
Definition at line 20 of file GUI_constructor.cpp.
References ui.
void GUI::set_validators () [private]
Set validators for user input.
Definition at line 34 of file GUI_constructor.cpp.
References ui.
QString GUI::valid_input () [private]
Check that all input needed is filled.
Definition at line 79 of file GUI_startButton.cpp.
References fill_rank(), fm, fori, Neural_Network::get_output_len(), File_Manager::get_rank_output_strings(), File_Manager::n, and ui.
Member Data Documentation
QFileDialog GUI::fileDialog [private]
Definition at line 21 of file GUI.h.
QString GUI::filePath [private]
Definition at line 20 of file GUI.h.
File_Manager GUI::fm [private]
Definition at line 48 of file GUI.h.
QByteArray GUI::state [private]
Definition at line 22 of file GUI.h.
Ui::GUI* GUI::ui [private]
Definition at line 46 of file GUI.h.
Author
Generated automatically by Doxygen from the source code.