.TH "phenogene/GUI_constructor.cpp" 3 "Fri Jun 21 2013" "Version 1.0" "Phenogene" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/GUI_constructor.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GUI\&.h>\fP
.br
\fC#include <ui_phenogene\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Phenogene from the source code\&.
