.TH "phenogene/GUI_startButton.cpp" 3 "Sat Jun 22 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/GUI_startButton.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GUI\&.h>\fP
.br
\fC#include <ui_phenogene\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
