.TH "phenogene/main.cpp" 3 "Fri Jun 21 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <GUI\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 4 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
