.TH "phenogene/NeuralNetwork.h" 3 "Fri Jun 21 2013" "Version 1.0" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/NeuralNetwork.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <General_Notation\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNeural_Network\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen from the source code\&.
