Neural_Network
NAME
Neural_Network -
SYNOPSIS
#include <NeuralNetwork.h>
Public Member Functions
Neural_Network ()
Neural Network class constructor.
void set_input_len (int)
Set number of input nodes to int i.
void set_output_len (int)
Set number of output to int i.
void set_hidden_len (int)
Set hidden nodes to int i.
void set_AV (int)
Set Activation function to be used to int i.
void set_minimum_error (double)
Set minimum error to double d.
void set_learning_rate (double)
Set learning rate to double d.
int get_input_len ()
Get int number of input nodes.
int get_output_len ()
Get int number of output nodes.
int get_hidden_len ()
Get int number of hidden nodes.
void do_function (int)
Train or test the network.
Private Member Functions
void init ()
Initialize weights and biases with values between -0.5 and 0.5.
void train ()
Train the neural network:
void test ()
Test the neural network.
double segmoidal_fn (double, int)
Calculates the segmoidal/segmoidal inverse of a double [x].
void propagate ()
Propagate input starting from the input layer up to the output layer. Uses softmax activation function.
double cal_error ()
Calculate the error signal for each node. Uses corss entropy error function.
void back_propagate ()
Back propagate the error starting from the output layer down to the input layer.
bool input_absent ()
void calculate_net (double &, double &)
Calculates the net for each node.
Private Attributes
int input_len
int hidden_len
int output_len
int AV
int dataset_size
double error
double minimum_error
double learning_rate
double momentum
double input [input_l]
double hidden [hidden_l]
double output [output_l]
double netH [hidden_l]
double netO [output_l]
double expected_o [output_l]
double bias_O [output_l]
double bias_H [hidden_l]
double Wh [hidden_l][input_l]
double Wo [output_l][hidden_l]
double tempWo [output_l][hidden_l]
double delta_O [output_l]
double delta_H [hidden_l]
map< char, double > input_rank
map< string, int > output_rank
map< int, string > rank_output
vector< vector< double > > input_dataset
vector< vector< double > > output_dataset
Friends
class File_Manager
Detailed Description
Definition at line 6 of file NeuralNetwork.h.
Constructor & Destructor Documentation
Neural_Network::Neural_Network ()
Neural Network class constructor.
Definition at line 7 of file NN_constructor.cpp.
References AV, dataset_size, hidden_len, input_len, input_rank, learning_rate, minimum_error, momentum, output_len, and segmoidal.
Member Function Documentation
void Neural_Network::back_propagate () [private]
Back propagate the error starting from the output layer down to the input layer. Precondition:
Delta signal for each node has been calculated.
Bias and Weights doesn't hold garpage.
Postcondition:
Bias and Weights are updated.
Definition at line 211 of file NN.cpp.
References bias_H, bias_O, delta_H, delta_O, fori, forj, hidden, hidden_len, input, input_len, learning_rate, momentum, output_len, Wh, and Wo.
double Neural_Network::cal_error () [private]
Calculate the error signal for each node. Uses corss entropy error function. Returns:
[total error]
Precondition:
Actual output is calculated using function [propagate].
Postcondition:
Delta signal for all nodes is calculated.
Definition at line 239 of file NN.cpp.
References calculate_net(), delta_H, delta_O, expected_o, fori, forj, hidden_len, netH, netO, output, and output_len.
void Neural_Network::calculate_net (double &max, double &maxO) [private]
Calculates the net for each node. Precondition:
Input dataset is filled.
Weights dataset is initialized.
Postcondition:
Net is caculated for Output and Hidden nodes.
Definition at line 274 of file NN.cpp.
References fori, forj, hidden_len, input, input_len, netH, netO, output_len, Wh, and Wo.
void Neural_Network::do_function (intwhat)
Train or test the network. Parameters:
[what] Determines weather to train or to test.
Definition at line 7 of file NN.cpp.
References test(), and train().
int Neural_Network::get_hidden_len ()
Get int number of hidden nodes.
Definition at line 24 of file NN_getters.cpp.
References hidden_len.
int Neural_Network::get_input_len ()
Get int number of input nodes.
Definition at line 6 of file NN_getters.cpp.
References input_len.
int Neural_Network::get_output_len ()
Get int number of output nodes.
Definition at line 15 of file NN_getters.cpp.
References output_len.
void Neural_Network::init () [private]
Initialize weights and biases with values between -0.5 and 0.5.
Definition at line 55 of file NN.cpp.
References bias_H, bias_O, fori, forj, hidden_len, input_len, output_len, Wh, and Wo.
bool Neural_Network::input_absent () [private]
void Neural_Network::propagate () [private]
Propagate input starting from the input layer up to the output layer. Uses softmax activation function. Precondition:
Input dataset is filled
Postcondition:
Hidden and Output nodes are computed.
Definition at line 178 of file NN.cpp.
References calculate_net(), fori, hidden, hidden_len, netH, netO, output, and output_len.
double Neural_Network::segmoidal_fn (doublex, intmode) [private]
Calculates the segmoidal/segmoidal inverse of a double [x]. Parameters:
[mode] Determines weather to calculate segmoidal or inverse.
Definition at line 38 of file NN.cpp.
void Neural_Network::set_AV (inti)
Set Activation function to be used to int i. Parameters:
[int i] Activation function to be used.
Definition at line 34 of file NN_setters.cpp.
References AV.
void Neural_Network::set_hidden_len (inti)
Set hidden nodes to int i. Parameters:
[int i] Number of nodes on the hidden layer.
Definition at line 25 of file NN_setters.cpp.
References hidden_len.
void Neural_Network::set_input_len (inti)
Set number of input nodes to int i. Parameters:
[int i] Number of nodes on the input layer.
Definition at line 7 of file NN_setters.cpp.
References input_len.
void Neural_Network::set_learning_rate (doubled)
Set learning rate to double d. Parameters:
[double d] Learning rate of the neural network.
Definition at line 52 of file NN_setters.cpp.
References learning_rate.
void Neural_Network::set_minimum_error (doubled)
Set minimum error to double d. Parameters:
[double d] Least acceptable error.
Definition at line 43 of file NN_setters.cpp.
References minimum_error.
void Neural_Network::set_output_len (inti)
Set number of output to int i. Parameters:
[int i] Number of nodes on the output layer.
Definition at line 16 of file NN_setters.cpp.
References output_len.
void Neural_Network::test () [private]
Test the neural network. Precondition:
Input_dataset is filled.
Weights dataset is filled.
Postcondition:
Output is filled.
Definition at line 147 of file NN.cpp.
References dataset_size, error, expected_o, fori, forj, fork, input, input_dataset, input_len, output, output_dataset, output_len, pow(), and propagate().
void Neural_Network::train () [private]
Train the neural network: Until error is under threshold or maximum number of iterations is reached.
Precondition:
Input Dataset is filled.
Expected Output Dataset is filled.
Postcondition:
Weights are optimal.
Definition at line 89 of file NN.cpp.
References back_propagate(), cal_error(), dataset_size, error, expected_o, fori, fork, init(), input, input_dataset, input_len, max_iterations, minimum_error, output_dataset, output_len, and propagate().
Friends And Related Function Documentation
friend class File_Manager [friend]
Definition at line 8 of file NeuralNetwork.h.
Member Data Documentation
int Neural_Network::AV [private]
Definition at line 33 of file NeuralNetwork.h.
double Neural_Network::bias_H[hidden_l] [private]
Definition at line 48 of file NeuralNetwork.h.
double Neural_Network::bias_O[output_l] [private]
Definition at line 47 of file NeuralNetwork.h.
int Neural_Network::dataset_size [private]
Definition at line 34 of file NeuralNetwork.h.
double Neural_Network::delta_H[hidden_l] [private]
Definition at line 57 of file NeuralNetwork.h.
double Neural_Network::delta_O[output_l] [private]
Definition at line 56 of file NeuralNetwork.h.
double Neural_Network::error [private]
Definition at line 35 of file NeuralNetwork.h.
double Neural_Network::expected_o[output_l] [private]
Definition at line 46 of file NeuralNetwork.h.
double Neural_Network::hidden[hidden_l] [private]
Definition at line 42 of file NeuralNetwork.h.
int Neural_Network::hidden_len [private]
Definition at line 31 of file NeuralNetwork.h.
double Neural_Network::input[input_l] [private]
Definition at line 41 of file NeuralNetwork.h.
vector<vector<double> > Neural_Network::input_dataset [private]
Definition at line 68 of file NeuralNetwork.h.
int Neural_Network::input_len [private]
Definition at line 30 of file NeuralNetwork.h.
map<char,double> Neural_Network::input_rank [private]
Definition at line 60 of file NeuralNetwork.h.
double Neural_Network::learning_rate [private]
Definition at line 37 of file NeuralNetwork.h.
double Neural_Network::minimum_error [private]
Definition at line 36 of file NeuralNetwork.h.
double Neural_Network::momentum [private]
Definition at line 38 of file NeuralNetwork.h.
double Neural_Network::netH[hidden_l] [private]
Definition at line 44 of file NeuralNetwork.h.
double Neural_Network::netO[output_l] [private]
Definition at line 45 of file NeuralNetwork.h.
double Neural_Network::output[output_l] [private]
Definition at line 43 of file NeuralNetwork.h.
vector<vector<double> > Neural_Network::output_dataset [private]
Definition at line 69 of file NeuralNetwork.h.
int Neural_Network::output_len [private]
Definition at line 32 of file NeuralNetwork.h.
map<string,int> Neural_Network::output_rank [private]
Definition at line 63 of file NeuralNetwork.h.
map<int,string> Neural_Network::rank_output [private]
Definition at line 65 of file NeuralNetwork.h.
double Neural_Network::tempWo[output_l][hidden_l] [private]
Definition at line 53 of file NeuralNetwork.h.
double Neural_Network::Wh[hidden_l][input_l] [private]
Definition at line 51 of file NeuralNetwork.h.
double Neural_Network::Wo[output_l][hidden_l] [private]
Definition at line 52 of file NeuralNetwork.h.
Author
Generated automatically by Doxygen from the source code.