.TH "phenogene/NN.cpp" 3 "Fri Jun 21 2013" "Version 1.0" "Phenogene" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phenogene/NN.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <NeuralNetwork\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBpow\fP (double x, double y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double pow (doublex, doubley)"

.PP
Definition at line 27 of file NN\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Phenogene from the source code\&.
